[package]
name = "ellastic-logging"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0"
authors = ["playfairs"]
repository = "https://github.com/playfairs/ellastic"
homepage = "https://tiffiny.org"

[dependencies]
ellastic-errors = { path = "../errors" }
tracing = { workspace = true }
tracing-core = "0.1"
tracing-subscriber = { workspace = true }
tracing-appender = "0.2"
tracing-error = "0.2"
color-eyre = "0.6"
directories = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
